name: ci
on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        node: [22, 24, 26]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          cache: pnpm
          node-version: ${{matrix.node}}
      - run: make lint

  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          cache: pnpm
          node-version: 24
      - run: make build
      - run: make test
